[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'

[tool.ruff]
select = ["E", "F", "B"]
unfixable = ["B"]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
line-length = 120
target-version = "py311"

# Ignore `E402` (import violations) in all `__init__.py` files
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"blog/settings.py" = ["E501"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.11"
disallow_untyped_defs = true

[tool.django-stubs]
django_settings_module = "blog_website.settings"